### ISSUE TITLE
when try to run      python train.py --device 0 --config config_SIDD_Val.json --tag SIDD_Val

### ISSUE THREAD

**Issue by cy163** [Reyhanehne/CVF-SID_PyTorch#1]
FileNotFoundError: [Errno 2] No such file or directory: '../data/SIDD_Small_sRGB_Only/ValidationGtBlocksSrgb.mat'

**Comment by lulu-165** [comment]
i have the same issues

**Comment by myavartanoo** [comment]
To train and evaluate the model directly please visit [SIDD](https://www.eecs.yorku.ca/~kamel/sidd/benchmark.php) websites and download the original `Noisy sRGB data` and `Ground-truth sRGB data` from `SIDD Validation Data and Ground Truth` and place them in `data/SIDD_Small_sRGB_Only` folder.
